```{r setup}
library(tidyr)
library(readr)
library(dplyr)
library(stringr)
library(magrittr)
library(glptools)
library(purrr)
library(leaflet)

library(broom)
library(purrr)

library(feather)
library(classInt)
library(scales)
library(ggplot2)
library(ggthemes)
library(ggrepel)
library(showtext)

showtext_auto()
font_add("Museo Sans 300", "MuseoSans_300.otf")
font_add("Museo Sans 300 Italic", "MuseoSans_300_Italic.otf")
```

```{r read_data}
individual_giving <- read_csv("output_data/charitable_giving.csv")

cra_county <- read_csv("output_data/CRA_county.csv")
cra_tract  <- read_csv("output_data/CRA_tract.csv", col_types = "cnnn")
cra_nh     <- read_csv("output_data/CRA_nh.csv")
cra_muw    <- read_csv("output_data/CRA_muw.csv")

sba_county <- read_csv("output_data/SBA_county.csv")

cdfi_county <- read_csv("output_data/CDFI_county.csv")
cdfi_tract  <- read_csv("output_data/CDFI_tract.csv")
cdfi_nh     <- read_csv("output_data/CDFI_nh.csv")
cdfi_muw    <- read_csv("output_data/CDFI_muw.csv")

local_govt <- read_csv("output_data/local_government_spending.csv")

cra_tract %<>% filter(year == 2018)
cra_nh    %<>% filter(year == 2018)
cra_muw   %<>% filter(year == 2018)

map_tract <- glptools:::map_tract
map_nh    <- glptools:::map_nh
map_muw   <- glptools:::map_muw

map_tract@data %<>% left_join(cra_tract, "tract")
map_nh@data    %<>% left_join(cra_nh,    "neighborhood")
map_muw@data   %<>% left_join(cra_muw,   "neighborhood")
```

```{r charitable_giving}
setwd("output_images/individual_giving")

png("individual_giving_percent_income_donated_agi7.png", 3000, 2400, res = 200)
ranking(filter(individual_giving, agi == 7),
        giving_pct_income, 
        plot_title = "Percent of Income Donated",
        subtitle_text = "AGI over $200,000",
        caption_text = "Source: Greater Louisville Project
                        IRS Statistics of Income")
dev.off()

png("individual_giving_percent_income_donated_agi6.png", 3000, 2400, res = 200)
ranking(filter(individual_giving, agi == 6),
        giving_pct_income, 
        plot_title = "Percent of Income Donated",
        subtitle_text = "AGI between $100,000 and $200,000",
        caption_text = "Source: Greater Louisville Project
                        IRS Statistics of Income")
dev.off()

png("individual_giving_agi7.png", 3000, 2400, res = 200)
trend(filter(individual_giving, agi == 7), 
      giving_pct_income, 
      plot_title = "Percent of Income Donated",
      subtitle_text = "AGI over $200,000",
      y_title = "Percent",
      label_function = percent_format(accuracy = 0.1, scale = 1),
      axis_function =  percent_format(accuracy = 0.1, scale = 1),
      caption_text = "Source: Greater Louisville Project
                      IRS Statistics of Income")
dev.off()

png("individual_giving_percent_donating.png", 3000, 2400, res = 200)
ranking(filter(individual_giving, agi == 7),
        donating_pct, 
        plot_title = "Percent of Filers Reporting Charitable Deductions",
        subtitle_text = "AGI over $200,000",
        caption_text = "Source: Greater Louisville Project
                        IRS Statistics of Income")
dev.off()

png("individual_giving_percent_agi_donated_agi7.png", 3000, 2400, res = 200)
ranking(filter(individual_giving, agi == 7),
        giving_pct_agi, 
        plot_title = "Percent of AGI Donated",
        subtitle_text = "AGI over $200,000",
        caption_text = "Source: Greater Louisville Project
                        IRS Statistics of Income")
dev.off()

individual_giving_gap <- individual_giving %>%
  filter(agi == 7, year == 2017) %>%
  mutate(percent_gap =  mean(giving_pct_income[FIPS != "21111"]) - giving_pct_income[FIPS == "21111"],
         dollar_gap  = percent_gap / 100 * avg_income[FIPS == "21111"] * total_returns) %>%
  filter(FIPS == "21111") %>%
  transmute(
    percent_gap = scales::percent(percent_gap, scale = 1, accuracy = 0.1), 
    dollar_gap  = scales::dollar(dollar_gap))
```

```{r local_government}
png("output_images/local_govt_spend_ranking.png", 3000, 2400, res = 200)
ranking(local_govt,
        "local_spend",
        plot_title = "Local Government Spending per capita, 2018",
        subtitle_text = "General fund expenditures",
        y_title = "Dollars",
        sigfig = 4,
        label_function = scales::dollar_format(accuracy = 1),
        caption = "Source: Greater Louisville Project
                   Data from Liz Farmer's analysis of city and county CAFRs")
dev.off()
```

```{r CRA}
png("output_images/CRA/CRA_ranking.png", 3000, 2400, res = 200)
ranking(cra_county, 
        amount_business_1m_pp,
        plot_title = "Bank Loans to Small Businesses per capita, 2018",
        subtitle_text = "Adjusted for inflation",
        y_title = "Dollars",
        label_function = scales::dollar_format(accuracy = 1),
        caption_text = "Source: Greater Louisville Project
                        Data from FFIEC CRA Reports")
dev.off()

png("output_images/CRA/CRA_trendline.png", 3000, 2400, res = 200)
trend(cra_county, 
      amount_business_1m_pp,
      plot_title = "Bank Loans to Small Businesses per capita",
      subtitle_text = "Adjusted for inflation",
      y_title = "Dollars",
      label_function = scales::dollar_format(accuracy = 1),
      caption_text = "Source: Greater Louisville Project
                      Data from FFIEC CRA Reports")
dev.off()

m <- make_map(list(map_tract, map_nh, map_muw),
              "amount_business_1m_pp",
              "Bank Loans to Small Business",
              "Loans per capita",
              units = "Dollars",
)

setwd("output_images/CRA")
htmlwidgets::saveWidget(m, "cra_map.html")
setwd("../..")

m <- make_map(list(map_tract, map_nh, map_muw),
              "amount_business_1m_pp",
              "Bank Loans to Small Business",
              "Loans per capita",
              units = "Dollars",
)

setwd("output_images/CRA")
htmlwidgets::saveWidget(m, "cra_map.html")
setwd("../..")
```

```{r SBA}
png("output_images/SBA/SBA_ranking.png", 3000, 2400, res = 200)
ranking(sba_county, 
        sba_loan_7a_pp,
        year = 2019,
        plot_title = "SBA 7(a) Small Business Loans per capita, 2019",
        subtitle_text = "Adjusted for inflation",
        y_title = "Dollars",
        label_function = scales::dollar_format(accuracy = 1),
        caption_text = "Source: Greater Louisville Project
                        Data from the U.S. Small Business Adminitration")
dev.off()

png("output_images/SBA/SBA_trendline.png", 3000, 2400, res = 200)
trend(sba_county, 
      sba_loan_7a_pp,
      rollmean = 3,
      plot_title = "SBA 7(a) Small Business Loans per capita",
      subtitle_text = "Adjusted for inflation",
      y_title = "Dollars",
      label_function = scales::dollar_format(accuracy = 1),
      axis_function = scales::dollar_format(accuracy = 1),
      caption_text = "Source: Greater Louisville Project
                      Data from the U.S. Small Business Adminitration")
dev.off()

```

```{r CDFI}
png("output_images/CDFI/CDFI_ranking.png", 3000, 2400, res = 200)
ranking(cdfi_county, 
        cdfi_pp,
        plot_title = "CDFI Investment per capita, 2017",
        subtitle_text = "Adjusted for inflation",
        y_title = "Dollars",
        label_function = scales::dollar_format(accuracy = 0.01),
        sigfig = 5,
        alternate_text = 9:17,
        caption_text = "Source: Greater Louisville Project
                        Data from the CDFI Program Data Release")
dev.off()

png("output_images/CDFI/CDFI_trendline.png", 3000, 2400, res = 200)
trend(cdfi_county, 
      cdfi_pp,
      plot_title = "CDFI Investment per capita",
      subtitle_text = "Adjusted for inflation",
      y_title = "Dollars",
      label_function = scales::dollar_format(accuracy = 0.01),
      axis_function  = scales::dollar_format(accuracy = 1),
      ylimits = c(0, 36),
      caption_text = "Source: Greater Louisville Project
                      Data from the CDFI Program Data Release")
dev.off()
```

```{r VC}
pitchbook <- glpdata:::pitchbook_msa_1yr

png("output_images/VC/vc_ranking.png", 3000, 2400, res = 200)
ranking(pitchbook, 
        total_dollars_pc,
        year = 2017:2019,
        plot_title = "Venture Capital Investment per capita, 2017-2019",
        y_title = "Dollars",
        label_function = dollar_format(accuracy = 1),
        alternate_text = 11:17,
        caption_text = "Source: Greater Louisville Project
                        Pitchbook Data Extract
                        MSA-level data")
dev.off()

png("output_images/VC/vc_trend.png", 3000, 2400, res = 200)
trend(pitchbook, 
      total_dollars_pc,
      rollmean = 3,
      plot_title = "Venture Capital Investment per capita",
      y_title = "Dollars",
      label_function = dollar_format(accuracy = 1),
      axis_function = dollar_format(accuracy = 1),
      caption_text = "Source: Greater Louisville Project
                      Pitchbook Data Extract
                      MSA-level data")
dev.off()

png("output_images/VC/deals_trend.png", 3000, 2400, res = 200)
trend(pitchbook, 
      deals_per_100000,
      #rollmean = 3,
      plot_title = "Venture Capital Deals per capita",
      y_title = "Deals per 100,000 residents",
      label_function = dollar_format(accuracy = 1),
      axis_function = dollar_format(accuracy = 1),
      caption_text = "Source: Greater Louisville Project
                      Pitchbook Data Extract
                      MSA-level data")
dev.off()

png("output_images/VC/median_deal_trend.png", 3000, 2400, res = 200)
trend(pitchbook, 
      median_deal,
      #rollmean = 3,
      plot_title = "Median VC Deal Size",
      y_title = "Dollars",
      label_function = dollar_format(accuracy = 1),
      axis_function = dollar_format(accuracy = 1),
      caption_text = "Source: Greater Louisville Project
                      Pitchbook Data Extract
                      MSA-level data")
dev.off()

```

```{r}
png("fortune_1000_raw.png", 3000, 2400, res = 200)
ranking(fortune, 
      fortune_1000, 
      plot_title = "Fortune 1000 Companies",
      y_title = "Companies",
      label_function = comma_format(accuracy = 1),
      caption_text = "Source: Greater Louisville Project
                      Pitchbook Data Extract
                      MSA-level data")
dev.off()

png("fortune_1000_pop_adj.png", 3000, 2400, res = 200)
ranking(fortune, 
      fortune_1000_per_lou, 
      plot_title = "Fortune 1000 Companies",
      subtitle_text = "Peer city data scaled to Louisville's population",
      label_function = comma_format(accuracy = 0.1),
      y_title = "Companies",
      caption_text = "Source: Greater Louisville Project
                      Pitchbook Data Extract
                      MSA-level data")
dev.off()
```

```{r}
educ   <- glpdata:::
jobs   <- glpdata::jobs_county
health <- glpdata::health_county
qop    <- glpdata::qop_county




```

