---
title: "The Flow of Community Investment: 2019 Conpetitive City Report"
output: 
  html_document
---


<style type="text/css"> 
h1 { 
  text-align: center; 
} 
h1,h2,h3,h4,h5,h6 { 
  font-family: "Museo Sans 300"; 
} 
body{ 
  font-family: "Museo Sans 300"; 
  text-align: center;
  font-size: 15px; 
} 
</style>

This is a deep dive into the data and methodology behind the Greater Louisville Project's 2019 Competitive City Report.

As a companion to our published report, this site provides more data, specific dollar amounts, and information about our methodology. The data and analysis included in this year's report is complex, and many steps along the way involve human judgement. We have engaged outside experts, run multiple analyses, and consulted community partners to help us verify our conclusions. In the interest of transparency, this page explores some of the alternative decisions that could have been made during our analysis and how they impact the results. We have found that while these decisions can have large impacts on the final dolar amounts, our standing among our peer cities is typically very consistent.

To the fullest extent possible, we make available all of the data and analysis used to create this report. You can find the raw data and the code used to analyse it here: https://github.com/greaterlouisvilleproject/CCU19.